# Generated by Django 4.1.7 on 2023-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('alias', models.CharField(max_length=55, verbose_name='Псевдоним')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('preview', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='authors/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название')),
                ('preview', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='genres/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField(max_length=255, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('photo', models.ImageField(upload_to='works/%Y/%m/%d/', verbose_name='Фото')),
                ('authors', models.ManyToManyField(to='Literature.author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(to='Literature.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='genres',
            field=models.ManyToManyField(blank=True, to='Literature.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(blank=True, to='Literature.work', verbose_name='Работы'),
        ),
    ]
