# Generated by Django 4.1.7 on 2023-05-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0002_alter_author_options_workcomment_genrecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=55, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='authors/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='photo',
            field=models.ImageField(blank=True, upload_to='genres/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(blank=True, upload_to='works/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
