# Generated by Django 4.1.7 on 2023-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0003_alter_author_alias_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='works',
        ),
    ]
