# Generated by Django 4.2.1 on 2023-05-23 12:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
        ('Literature', '0004_remove_author_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='likes',
            field=models.ManyToManyField(blank=True, to='Members.profile', verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='genre',
            name='likes',
            field=models.ManyToManyField(blank=True, to='Members.profile', verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='work',
            name='likes',
            field=models.ManyToManyField(blank=True, to='Members.profile', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='author',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
