# Generated by Django 4.2.1 on 2023-05-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Literature', '0005_author_likes_genre_likes_work_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='authorcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='genrecomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='work',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='workcomment',
            name='likes',
        ),
    ]
